// Mocks generated by Mockito 5.4.2 from annotations
// in project_learn_clean_architecture/test/features/auth/domain/usescases/register_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:project_learn_clean_architecture/core/error/failures.dart'
    as _i5;
import 'package:project_learn_clean_architecture/core/usecases/usecases.dart'
    as _i6;
import 'package:project_learn_clean_architecture/features/auth/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failures, bool>> register(_i6.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failures, bool>>.value(
            _FakeEither_0<_i5.Failures, bool>(
          this,
          Invocation.method(
            #register,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, bool>>.value(
                _FakeEither_0<_i5.Failures, bool>(
          this,
          Invocation.method(
            #register,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failures, bool>> logIn(_i6.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #logIn,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failures, bool>>.value(
            _FakeEither_0<_i5.Failures, bool>(
          this,
          Invocation.method(
            #logIn,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, bool>>.value(
                _FakeEither_0<_i5.Failures, bool>(
          this,
          Invocation.method(
            #logIn,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, bool>>);
  @override
  _i2.Either<_i5.Failures, bool> checkLogined() => (super.noSuchMethod(
        Invocation.method(
          #checkLogined,
          [],
        ),
        returnValue: _FakeEither_0<_i5.Failures, bool>(
          this,
          Invocation.method(
            #checkLogined,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeEither_0<_i5.Failures, bool>(
          this,
          Invocation.method(
            #checkLogined,
            [],
          ),
        ),
      ) as _i2.Either<_i5.Failures, bool>);
  @override
  _i2.Either<_i5.Failures, bool> logOut() => (super.noSuchMethod(
        Invocation.method(
          #logOut,
          [],
        ),
        returnValue: _FakeEither_0<_i5.Failures, bool>(
          this,
          Invocation.method(
            #logOut,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeEither_0<_i5.Failures, bool>(
          this,
          Invocation.method(
            #logOut,
            [],
          ),
        ),
      ) as _i2.Either<_i5.Failures, bool>);
}
